In [1]:
import numpy as np
import math

In [2]:
a = np.exp(-math.log(10)/3)
a

np.float64(0.46415888336127786)

In [7]:
b = 1 / 10**(1/3)
b

0.46415888336127786

In [ ]:
c = 

In [8]:
import torch


In [11]:
q_len = 4
k_len = 4
mask = torch.tril(torch.ones(q_len, k_len)).view(1, 1, q_len, k_len)
print(mask)
mask = mask.masked_fill(mask==0,float('-inf'))
mask = mask.masked_fill(mask==1, 0)

tensor([[[[1., 0., 0., 0.],
          [1., 1., 0., 0.],
          [1., 1., 1., 0.],
          [1., 1., 1., 1.]]]])


In [10]:
mask

tensor([[[[0., -inf, -inf, -inf],
          [0., 0., -inf, -inf],
          [0., 0., 0., -inf],
          [0., 0., 0., 0.]]]])

In [12]:
mask.shape

torch.Size([1, 1, 4, 4])

In [20]:
past_len=3
q_len = 2
k_len = 5
q_pos = torch.arange(q_len)[:, None]
k_pos = torch.arange(k_len)[None, :]

allowed = k_pos <= (past_len + q_pos)
print(allowed)

tensor([[ True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True]])


In [22]:
a = torch.rand((3,4))
print(a)
print(torch.softmax(a, dim=1))

tensor([[0.8379, 0.7970, 0.8884, 0.3279],
        [0.4045, 0.6685, 0.2907, 0.4075],
        [0.6360, 0.7530, 0.2276, 0.9035]])
tensor([[0.2768, 0.2658, 0.2912, 0.1662],
        [0.2382, 0.3102, 0.2126, 0.2390],
        [0.2442, 0.2745, 0.1623, 0.3191]])
